### ISSUE TITLE
help: stuck at the Init Telegram Bot API Webhook step

### ISSUE THREAD

**Issue by rozhandad** [mini-woo/mini-woo#2]
Hello
Thank you for this program
I'm stuck at the  **### Init Telegram Bot API Webhook** step
I don't know how to do this part
please help
And is it possible to create a program for a WordPress blog?

**Comment by parvardegr** [comment]
hi @rozhandad 
you need to send a http request to telegram, the curl instruction is provided in the documentatiom, you can also call this api use Postman or whatever you are more comfortable with 🤘
